export const DashboardType = {
  API_GET_LIST_REQUEST: "API_GET_LIST_REQUEST",
  API_GET_LIST_SUCESS: "API_GET_LIST_SUCESS",
  API_GET_LIST_FAIL: "API_GET_LIST_FAIL",

  API_GET_LIVE_CHATS: "API_GET_LIVE_CHATS",
};
